# Generated by Django 6.0 on 2025-12-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('D_Name', models.CharField(max_length=100)),
                ('D_EMail', models.EmailField(max_length=254, unique=True)),
                ('D_Phone', models.IntegerField(max_length=12)),
            ],
        ),
    ]
