# Generated by Django 6.0 on 2025-12-12 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('pickup_location', models.CharField(max_length=200)),
                ('dropoff_location', models.CharField(max_length=200)),
                ('pickup_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('vehicle_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('R_Start', models.CharField(max_length=100)),
                ('R_End', models.CharField(max_length=100)),
                ('R_Distance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Deliveries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('D_Item', models.CharField(max_length=200)),
                ('D_Weight', models.FloatField()),
                ('Delivery_Date', models.DateField()),
                ('Route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.routes')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('V_Number', models.CharField(max_length=20, unique=True)),
                ('V_Type', models.CharField(max_length=50)),
                ('V_Capacity', models.IntegerField()),
                ('Driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.drivers')),
            ],
        ),
        migrations.AddField(
            model_name='routes',
            name='Vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.vehicles'),
        ),
    ]
